Update args.py
if args.trade.id[0] == '@':
AttributeError: 'Namespace' object has no attribute 'trade'

The period needs to be deleted between 'trade' and 'id'.